### ISSUE TITLE
Publish new versions to Anaconda

### ISSUE THREAD

**Issue by daneah** [ithaka/apiron#104]
**Is your feature request related to a problem? Please describe.**
Many people using Python use Anaconda to manage their packages and runtime environment. Anaconda can't install packages directly from PyPI, instead requiring users to run several commands if they want Anaconda to manage a package for them.

**Describe the solution you'd like**

In addition to publishing to PyPI, building the package with `conda` and publishing it to Anaconda would help people using Anaconda install and use this package.

**Describe alternatives you've considered**

The manual process for using packages from PyPI looks like this with Anaconda:

```shell
$ conda skeleton pypi apiron
$ conda build apiron
$ conda install --use-local apiron
```

Users can also use `pip`, but lose out on the management Anaconda would provide around updating versions, etc.

**Comment by daneah** [comment]
It would be interesting to see if [recent Anaconda improvements](https://stackoverflow.com/a/57522799/2077393) make this less valuable.

**Comment by NazimHAli** [comment]
> It would be interesting to see if [recent Anaconda improvements](https://stackoverflow.com/a/57522799/2077393) make this less valuable.

I've been using `pip install` for packages not available through Anaconda and it's been working well/seamless in `conda` environments. Unless we have non-Python requirements, I don't think it would provide any value other than running a different command.

**Comment by daneah** [comment]
Thanks for the input @NazimAli2017, I think we can close this for the moment!
