### ISSUE TITLE
Non-intuitive behavior with non-root endpoints

### ISSUE THREAD

**Issue by teffalump** [ithaka/apiron#13]
**Describe the bug**
Non-root endpoints - e.g., example.com/rest - behave non-intuitively when paired with their endpoints.

**To Reproduce**
1. Define: domain = 'https://example.com/server'
1. Add some endpoints: test = JsonEndpoint('/test')
1. Call endpoint: client queries url https://example.com/test

**Expected behavior**
The intuitive behavior is joining the full domain with the endpoint. That is, 'https://example.com/server/test'

**What actually happened**
The culprit is urllib.parse.urljoin. It is quite fastidious about joining urls. The 'workaround' is that you must define the domain with a trailing slash and the endpoint missing its leading slash.

**Additional context**
There are other combos that create non-intuitive joins. On the one hand, urllib.parse.urljoin is most certainly correct in how it goes about joining. On the other hand, as many rest endpoints are not placed on the root of the server, I do believe some clarification is needed. Domain and endpoint definition probably shouldn't require understanding urljoin specifics. There are no doubt a few choices here. Easiest is likely more documentation, which I can help add if that's the route you choose. I believe forcing domains to trailing slashes and removing leading slashes from endpoints would work, but I'm not sure about full consequences.

Anyways, thanks for great library!

**Comment by daneah** [comment]
Thanks for pointing this out @teffalump! We have this same use case ourselves, now that I'm thinking about it, since some of the APIs we work with are versioned and live at `https://some-api.com/v1/`, for example. Up to now we've just placed the `v1` into each of the endpoints' `path`s, which isn't a great solution, especially for APIs with many endpoints.

One way we could approach this would be to more liberally accept domain/endpoint combinations with improper slashes and smartly join them correctly under the hood. That could cover the following cases:

```
domain = 'https://some-api.com',     endpoint='/foo'
domain = 'https://some-api.com/',    endpoint='foo'
domain = 'https://some-api.com',     endpoint='foo'
domain = 'https://some-api.com/',    endpoint='/foo'
domain = 'https://some-api.com/v1',  endpoint='/foo'
domain = 'https://some-api.com/v1/', endpoint='foo'
domain = 'https://some-api.com/v1',  endpoint='foo'
domain = 'https://some-api.com/v1/', endpoint='/foo'
```

What do you think?

**Comment by teffalump** [comment]
Hi @daneah! I like that idea - checking for those base cases. Something like:

    domain = domain if domain.endswith('/') else '/'.join([domain, ''])
    path = endpoint.lstrip('/')

Then passing those values to urljoin. There are edge cases where the root domain may not hold all the endpoints. For example:

    domain = 'https://some-api.com/most-fxns'
    endpoint = 'normal-fxn'
    endpoint = '/core/core-fxn'       #should be https://some-api.com/core/core-fxn

However, that seems overkill to check for. I suppose adding an option to ignore this helper functionality is possible. Otherwise, can also define a new `Service` with `Endpoint`s to handle a new base domain, or something like that. Anyways, those are my thoughts - thanks for response!

**Comment by daneah** [comment]
Cool, we can definitely think on this for the next release and we're also happy to consider and work with you on a pull request if you have the time! Stay tuned.

**Comment by teffalump** [comment]
Tried to follow the commit message guidelines but was flailing with good intentions.
