### ISSUE TITLE
Version 8.0.0 not fully published

### ISSUE THREAD

**Issue by michael-iden** [ithaka/apiron#135]
**Describe the bug**
Version 8.0.0 is not available in PyPI

**To Reproduce**
1. https://pypi.org/project/apiron/#history

**Expected behavior**
8.0.0 is available for download

**What actually happened**
7.1.0 looks to be the last published release

**Additional context**
https://github.com/ithaka/apiron/releases also shows the last release as 7.1.0

**Comment by michael-iden** [comment]
@eslawski Pointed out this might be intentional given the changelog
https://github.com/ithaka/apiron/blob/dev/CHANGELOG.md

I am currently running into problems with dependencies due to the cap on urllib that's in place for 7.1.0 but [has been fixed already in a merged PR](https://github.com/ithaka/apiron/pull/133/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52L36). 

Maybe we could cut an alpha/beta release?

**Comment by daneah** [comment]
@michael-iden can you clarify if you're just asking for the current set of changes in the mainline to be released as a new major version, or have you noticed an 8.0.0 release referenced somewhere?

Edit: I see it in `setup.cfg`, which might be what led you to believe it should be published. This was updated only in preparation for eventual release, but I see why it could be confusing. If you ultimately need a release to unblock on `urllib` version, I can do that!

**Comment by michael-iden** [comment]
Yes to all the above! Thanks!

**Comment by daneah** [comment]
[v8.0.0 has been released](https://pypi.org/project/apiron/8.0.0/).
