### ISSUE TITLE
StubEndpoint not callable

### ISSUE THREAD

**Issue by daneah** [ithaka/apiron#37]
**Describe the bug**
Using the syntax released in v2.3.0 for `StubEndpoint`s raises a `TypeError`.

**To Reproduce**

```python
from apiron.endpoint.stub import StubEndpoint
from apiron.service.base import Service

class MyService(Service):
    domain = 'myservice.com'

    my_endpoint = StubEndpoint(stub_response=lambda **kwargs: 'response')

MyService.my_endpoint()
# TypeError: 'StubEndpoint' object is not callable
```

**Expected behavior**
Calling the stub endpoint in this way should call `stub_response`, if it's callable, or return the value of `stub_response`.

**What actually happened**
A `TypeError` 😢 

**Environment:**
 - OS: macOS
 - Python version: 3.4.3
 - `apiron` version: 2.3.0

**Additional context**
This is happening since `StubEndpoint`s do not inherit from `Endpoint` and thus do not receive the metaprogramming treatment other `Endpoint` subclasses do. A fix would be to add the expected behavior described above in `ServiceMeta`.

**Comment by momo-sa** [comment]
@daneah Grabbing this if you don't mind. I'll work on it in the next few days.

**Comment by daneah** [comment]
@momo-sa it's possible just subclassing `Endpoint` for `StubEndpoint` could work, unless there's some other block along that path. That inheritance structure would still make sense.
