### ISSUE TITLE
Allow config for returning full `requests.Response`

### ISSUE THREAD

**Issue by kentjas1** [ithaka/apiron#82]
**Is your feature request related to a problem? Please describe.**
In some cases there are headers sent from the service endpoint that needs to be read and set on an outgoing response to a user. The current endpoints defined don't pass the headers returned from the service called.

**Describe the solution you'd like**
My first thought is that there would be a param passed when defining an `Endpoint` to return headers or return full requests similar to the `default_method`, `path` and other params that currently exist.

**Describe alternatives you've considered**
I have been able to extend `Endpoint` and overrode the `format_response` method to return `requests.Response` so that I can then read and set the delivered headers as needed.

**Additional context**
My main use case for needing this is for a service endpoint that generates and delivers a file. The service sets `Content-Disposition`, `Content-Type` and other headers that need to be passed to the outgoing file being delivered.

**Comment by daneah** [comment]
In #7 we made a case for getting the raw response object, but didn't feel it was quite warranted at the time. I think this makes a pretty strong case for being able to get the raw response and all the additional information that comes along with it. Let's revisit that changeset and see how it compares with what we have now!
