### ISSUE TITLE
Option to specify proxies

### ISSUE THREAD

**Issue by chankeypathak** [ithaka/apiron#95]
**Describe the bug**
I can't find a way to define proxy information, e.g. in requests we can say `requests.get('http://example.org', proxies=proxies)`

**To Reproduce**
Steps to reproduce the behavior: NA

**Expected behavior**
There should be an option to pass proxy information.

**What actually happened**
NA

**Screenshots**
NA

**Environment:**
 - OS: Any
 - Python version 3.7.5
 - `apiron` version 5.0.0

**Additional context**
I'm happy to contribute if you could walk me through the project.

**Comment by chankeypathak** [comment]
I think adding below to https://github.com/ithaka/apiron/blob/dev/src/apiron/client.py#L223 may help. But the variable `proxy` should be provided by user.

`session.proxies.update(<proxy>)`

**Comment by chankeypathak** [comment]
While at it, could you also share how to do HTTPBasicAuth using apiron? 

I use below in requests:

`requests.get('https://api.github.com/user', auth=HTTPBasicAuth('user', 'pass'))`

**Comment by daneah** [comment]
@chankeypathak This will indeed require an update to `client.py`. apiron passes several keyword arguments directly to `requests`—namely, [these](https://github.com/ithaka/apiron/blob/dev/src/apiron/client.py#L228-L238) which are used [here](https://github.com/ithaka/apiron/blob/dev/src/apiron/client.py#L117-L125). Adding `proxies` to this list should allow it to be used automatically in the underlying `requests` handling.

We would welcome a pull request with that change, if you're interested!
