### ISSUE TITLE
How to do HTTPBasicAuth using apiron?

### ISSUE THREAD

**Issue by chankeypathak** [ithaka/apiron#96]
**Describe the bug**
How to do HTTPBasicAuth using apiron?

**To Reproduce**
I use below in requests:

`requests.get('https://api.github.com/user', auth=HTTPBasicAuth('user', 'pass'))`

**Comment by daneah** [comment]
You can use the `auth` keyword argument when making the call:

```python
from apiron import Service, Endpoint


class HttpBin(Service):
    domain = 'https://httpbin.org'

    basic_auth = Endpoint(path='/basic-auth/{user}/{pw}')


if __name__ == '__main__':
    response = HttpBin.basic_auth(user='foo', pw='bar', auth=('foo', 'bar'))  # removing auth gives 401 Unauthorized
    print(response)
```

Please let us know if this works for you!

**Comment by chankeypathak** [comment]
@daneah Thanks! How about having `auth` for the `Service` so that user doesn't have to pass the same credentials for each and every `Endpoint` of a `Service`?

**Comment by daneah** [comment]
I think we could do that, similarly to #98. You _can_ also attach `auth` to a session and pass that session to your calls (this should work for `proxies`, too):

```python
import requests

from apiron import Service, Endpoint


class HttpBin(Service):
    domain = 'http://httpbin.org'

    anything = Endpoint(path='/anything')


if __name__ == '__main__':
    session = requests.Session()
    session.auth = ('foo', 'bar')
    session.proxies = {'http': '91.205.174.26'}

    response = HttpBin.anything(session=session)
    print(response)
```

That returns something like the following (note `headers.Authorization` and `origin` keys):

```json
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Authorization": "Basic Zm9vOmJhcg==",
    "Host": "httpbin.org",
    "User-Agent": "python-requests/2.20.0",
    "X-Amzn-Trace-Id": "Root=1-5ed26dcc-55448f88e320bc4e510263b4"
  },
  "json": null,
  "method": "GET",
  "origin": "91.205.174.26",
  "url": "https://httpbin.org/anything"
}
```

The way we've updated `proxies` in #98 makes a provided session's `proxies` value stop working, which I'm realizing isn't ideal. Will comment over there with a potential solution.

**Comment by daneah** [comment]
@chankeypathak did you plan to work on this change? I imagine it'd look similar to #98.

**Comment by chankeypathak** [comment]
@daneah Thanks for reminding. I'll work on it this week.

**Comment by chankeypathak** [comment]
@daneah Sorry I'm a bit overloaded right now. Can you update the test suite?

I see that it's failing due to below:

```
lint run-test: commands[1] | black --check src/apiron tests
would reformat /home/travis/build/ithaka/apiron/src/apiron/client.py
Oh no! 💥 💔 💥
1 file would be reformatted, 16 files would be left unchanged.
ERROR: InvocationError for command /home/travis/build/ithaka/apiron/.tox/lint/bin/black --check src/apiron tests (exited with code 1)
```

**Comment by daneah** [comment]
@chankeypathak no problem, thanks for doing what you had bandwidth for! I'll have a look today or tonight.
