### ISSUE TITLE
Proper way to use query parameters

### ISSUE THREAD

**Issue by chankeypathak** [ithaka/apiron#97]
I'm trying to access Morningstar API. With `requests` I can do below:

```python
requests.get("https://api.morningstar.com...../feeds/.../timeseries?Contract=<xyz>&Delivery=Dec19",
 proxies=myproxies, 
 auth=HTTPBasicAuth("<user>", "<password>"), 
 headers=myheaders
```
**Query 1:** How can I do it using apiron?

I tried below. It works but I don't think it's the right way to use apiron. I get the warning:

(`Endpoint path may contain query params, Use the default_params or required_params attirbutes....`). 

I tried providing `required_params` as a set but in that case there was no response from the vendor.

```python
class MS(Service):
    domain = 'https://api.morningstar.com...../feeds/.../'
    ts = JsonEndpoint(path='timeseries?Contract=<xyz>&Delivery=Dec19')

print(MS.ts())
```

**Query 2:** How can I pass auth and proxies information?

**Comment by kentjas1** [comment]
@chankeypathak, for your first question regarding the warning you are seeing. For url params that are the same value for every call to an endpoint, its best to use the `default_params` in the endpoint definition like this:

```python
class MS(Service):
    domain = 'https://api.morningstar.com'
    ts = JsonEndpoint(
        path='/.../feeds/.../timeseries',
        default_params={'Contract': '<xyz>', 'Delivery': 'Dec19'},
    )

MS.ts()
# results in a GET request to https://api.morningstar.com/.../feeds/.../timeseries?Contract=<xyz>&Delivery=Dec19
```
Now for parameters that are required to call the endpoint but the values will need to be dynamic at runtime, thats where `required_params` comes into play. Those are params that must be passed in order for Apiron to make the call. So say, using your example, that `Contract` will always be `<xyz>` but a different `Delivery` value is needing to be passed, you would have something like this:

```python
class MS(Service):
    domain = 'https://api.morningstar.com'
    ts = JsonEndpoint(
        path='/.../feeds/.../timeseries',
        default_params={'Contract': '<xyz>'},
        required_params={'Delivery'},
    )

MS.ts() # This will raise an UnfulfilledParameterException

MS.ts(params={'Delivery': 'Dec19'}) 
# results in a GET request to https://api.morningstar.com/.../feeds/.../timeseries?Contract=<xyz>&Delivery=Dec19
```

Let us know if this clarifies the usage or if you have any further questions.

**Comment by chankeypathak** [comment]
@kentjas1 Thank you. That's a very neat design. I like it.
Will follow the question related to `proxies` in #98
